#Default config file for eukdetect. Copy and edit for analysis


outputdir: "/path/to/analysis" #directory where output should be written
    
paired_end: true #true or false

fwd_suffix: "_1.fastq.gz" #filename excluding sample name. no need to edit if paired_end= false
rev_suffix: "_2.fastq.gz" #filename excludign sample name. no need to edit if paired_end = false
se_suffix: ".fastq.gz" #file name excluding sample name. no need to edit if paired_end = true
readlen: 125 #targeted length of your reads. pre-trimming reads not recommended

fq_dir: "fastq" #full path to directory with raw fastq files
database_dir: "/path/to/eukdetect/databases" #full path to folder with all eukdetect_db files and taxdump_1_14_2020.tar.gz file

eukdetect_dir: "/path/to/eukdetect/" #full path to eukdetect installation folder


samples: #list sample names here. fastqs must correspond to {samplename}{se_suffix} for SE reads or {samplename}{fwd_suffix} and {samplename}{rev_suffix} for PE
  sample1:
  sample2:
